# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aacf56706773b82b59dec789005e06db"
name = "listorderbackend"
handle = "listorderbackend"
application_url = "https://formatting-auditor-science-locks.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bistybue.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [
  "https://formatting-auditor-science-locks.trycloudflare.com/auth/callback",
  "https://formatting-auditor-science-locks.trycloudflare.com/auth/shopify/callback",
  "https://formatting-auditor-science-locks.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
